import { upload } from '@vercel/blob/client';

const slip=document.querySelector('#bet-slip'),content=document.querySelector('#bet-content'),count=document.querySelector('#bet-count'),stake=document.querySelector('#stake'),returnValue=document.querySelector('#return-value'),modal=document.querySelector('#login-modal'),uploadPanel=document.querySelector('#upload-panel'),imageUpload=document.querySelector('#image-upload'),uploadButton=document.querySelector('#upload-button'),uploadStatus=document.querySelector('#upload-status');let selection=null;
document.querySelector('.hero .kicker').innerHTML='<span class="pulse"></span> CARTOON MOVIES. BIG ADVENTURES.';document.querySelector('.hero h1').innerHTML='คืนนี้<br/><em>ดูเรื่องไหนดี</em>';document.querySelector('.hero-text').innerHTML='รวมหนังการ์ตูนสุดสนุก ตัวละครสุดป่วน และเรื่องราว<br/>ที่ทำให้ทุกวัยยิ้มได้ตั้งแต่ฉากแรกจนเครดิตจบ';document.querySelector('.hero .primary-button').innerHTML='เลือกหนังคืนนี้ <span>↓</span>';document.querySelector('.hero .text-button').innerHTML='ดูตัวอย่าง <span>→</span>';document.querySelector('.hero-number').textContent='★';document.querySelector('.hero-tag').innerHTML='CARTOON NIGHT<br/><span>NEW ADVENTURE</span>';document.querySelector('.ticker-label').textContent='NOW SHOWING';
const showLogin=()=>modal.classList.remove('hidden');
const updateSlip=()=>{if(!selection)return;count.textContent='1';content.className='selected-bet';content.innerHTML=`<button class="remove-bet" aria-label="ลบตัวเลือก">×</button><span>เลือกเดิมพัน</span><strong>${selection.label}</strong><b>@ ${selection.price.toFixed(2)}</b>`;returnValue.textContent=`฿${((Number(stake.value)||0)*selection.price).toLocaleString('th-TH',{minimumFractionDigits:2})}`;content.querySelector('.remove-bet').onclick=()=>{selection=null;count.textContent='0';content.className='empty-bet';content.innerHTML='<span>+</span><p>เลือกอัตราต่อรอง<br/>เพื่อเริ่มวางบิล</p>';returnValue.textContent='฿0.00'}};
document.querySelectorAll('[data-odd]').forEach(button=>button.onclick=()=>{const [label,price]=button.dataset.odd.split(' ');selection={label:`${label} ชนะ`,price:Number(price)};document.querySelectorAll('.odds button').forEach(el=>el.classList.remove('picked'));button.classList.add('picked');slip.classList.add('open');updateSlip()});
document.querySelectorAll('.bet-match').forEach(button=>button.onclick=()=>{selection={label:`${button.dataset.match} · ผู้ชนะ`,price:1.85};slip.classList.add('open');updateSlip()});stake.oninput=updateSlip;document.querySelector('.close-slip').onclick=()=>slip.classList.remove('open');document.querySelectorAll('.login-trigger,#place-bet').forEach(button=>button.onclick=showLogin);document.querySelector('.close-modal').onclick=()=>modal.classList.add('hidden');modal.onclick=event=>{if(event.target===modal)modal.classList.add('hidden')};
document.querySelector('#login-form').onsubmit=async event=>{event.preventDefault();const form=event.currentTarget,button=form.querySelector('button'),inputs=form.querySelectorAll('input');button.disabled=true;button.textContent='กำลังเข้าสู่ระบบ...';try{const response=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:inputs[0].value,password:inputs[1].value})});const data=await response.json();if(!response.ok)throw new Error(data.message||'เข้าสู่ระบบไม่สำเร็จ');localStorage.setItem('rush90-token',data.token);uploadPanel.classList.remove('hidden');modal.classList.add('hidden');document.querySelector('.login-trigger').textContent=`${data.user.name} ↗`}catch(error){button.textContent=error.message}finally{button.disabled=false;setTimeout(()=>{if(!button.disabled)button.innerHTML='เข้าสู่ระบบ <span>→</span>'},1800)}};
uploadButton.onclick=async()=>{const file=imageUpload.files[0],token=localStorage.getItem('rush90-token');if(!file||!token){uploadStatus.textContent='กรุณาเลือกไฟล์และเข้าสู่ระบบก่อน';return}uploadButton.disabled=true;uploadStatus.textContent='กำลังอัปโหลด...';try{const blob=await upload(file.name,file,{access:'public',handleUploadUrl:'/api/blob/client-token',headers:{Authorization:`Bearer ${token}`},onUploadProgress:({loaded,total})=>{uploadStatus.textContent=`กำลังอัปโหลด ${Math.round((loaded/total)*100)}%`}});uploadStatus.innerHTML=`อัปโหลดสำเร็จ: <a href="${blob.url}" target="_blank" rel="noreferrer">เปิดไฟล์</a>`}catch(error){uploadStatus.textContent=error.message||'อัปโหลดไม่สำเร็จ'}finally{uploadButton.disabled=false}};
document.querySelectorAll('.filter').forEach(button=>button.onclick=()=>{document.querySelectorAll('.filter').forEach(el=>el.classList.remove('active'));button.classList.add('active')});document.querySelectorAll('[data-scroll]').forEach(button=>button.onclick=()=>document.querySelector(button.dataset.scroll).scrollIntoView({behavior:'smooth'}));
